### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by wolfkin** [TexasLAN/Slack-Files-Download-Delete#1]
So I'm fairly new to this i assume I missed something obivous. 

I installed Python (Windows 10) 3.7

opened up command prompt, went to the file and it didn't work. Any chance you can help me figure out what I can do to fix it?

The only change I made was a true to false change here - https://i.imgur.com/62C1uMD.png

```
Microsoft Windows [Version 10.0.17134.285]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Admin>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> exit
Use exit() or Ctrl-Z plus Return to exit
>>> exit()

C:\Users\Admin>cd C:\Users\Admin\Downloads\Slack-Files-Download-Delete-master

C:\Users\Admin\Downloads\Slack-Files-Download-Delete-master>dir
 Volume in drive C has no label.

 Directory of C:\Users\Admin\Downloads\Slack-Files-Download-Delete-master

10/02/2018  09:47 AM    <DIR>          .
10/02/2018  09:47 AM    <DIR>          ..
09/16/2016  06:00 PM                85 .gitignore
09/16/2016  06:00 PM               421 README.md
10/02/2018  09:49 AM             1,481 slack_download_delete.py
               3 File(s)          1,987 bytes
               2 Dir(s)  35,879,444,480 bytes free

C:\Users\Admin\Downloads\Slack-Files-Download-Delete-master>slack_download_delete.py
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\Slack-Files-Download-Delete-master\slack_download_delete.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

C:\Users\Admin\Downloads\Slack-Files-Download-Delete-master>python slack_download_delete.py
Traceback (most recent call last):
  File "slack_download_delete.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by wolfkin** [comment]
a little investigating suggests that there's an undocumented dependency as referenced in [another project](https://github.com/marek/fslack), I think [requests](http://docs.python-requests.org/en/master/) is required.
